### ISSUE TITLE
GPS情報無い写真への対応

### ISSUE THREAD

**Issue by littletake** [littletake/supporterz_hackathon_2021#43]
# やること
- GPS情報がない写真をどう対応するか

# 対策
## フロント側で対応
- アップロード時にExifを見てGPS情報がない場合はエラーを出す

## バック側で対応
- デコードした段階で判別できるので結果をフロントに返す  
（エラーコードで対応？）

**Comment by pola5pola5** [comment]
送信前にエラーが出せたら操作性として良さそうだけど(カメラアイコンで列挙している時点)，デコード時の方が実装しやすいような感覚

**Comment by littletake** [comment]
> 送信前にエラーが出せたら操作性として良さそうだけど(カメラアイコンで列挙している時点)，デコード時の方が実装しやすいような感覚

そうだね、フロント側で写真を選択した時にexifをみてgps情報なければエラーを出す、みたいなのしたいね

**Comment by littletake** [comment]
バックエンド側で判定する場合だとサーバに送る手間がかかってしまうからフロント側で処理したい気持ち
どのくらい処理に時間かかるかわからないから実装して考えたい。。。

**Comment by pola5pola5** [comment]
フロント側で対応できそうなのでもう少々お待ちを...！

**Comment by littletake** [comment]
#52 
完了
