### ISSUE TITLE
s3の画像をフロントから直接取得

### ISSUE THREAD

**Issue by littletake** [littletake/supporterz_hackathon_2021#44]
# やること
- 画像をバックエンドを介してgetできるようにする。

**Comment by takeru0208** [comment]
# 現状の問題点
imgをアップロードした後サーバから画像の個数のjsonが返ってくる。
画像ごとのjsonにs3のurlがあり、初回マーカーをクリックするとurlから画像をgetし表示するようになっている。

現在はjavascriptのdocument.createElementでポップアップを表示
参考：https://developer.mozilla.org/ja/docs/Web/API/Document/createElement

参考：s3のurlに一時credentialを発行する仕組み
https://dev.classmethod.jp/articles/create-pre-signed-url-with-lambda/

**Comment by takeru0208** [comment]
# 暫定改善案
以下のurlを参考にして、ログインを行う時にCognioにユーザー登録し、そこでトークンを発行し、ログインしている状態であればs3objectを取得できるようにするのが良さげ。

参考url: http://penguinitis.g1.xrea.com/computer/programming/AWS/S3_web/S3_web.html

**Comment by takeru0208** [comment]
# 現在作成中のプログラム(2021/8/13)
javascriptでcognitoの認証および認証を使ったawsサービスへのアクセスを作成
参考1 ：[Amazon Cognitoを使ったサインイン画面をつくってみる～サインアップ編～](https://www.tdi.co.jp/miso/amazon-cognito-sign-up)
参考2 ：[javascriptからS3へのアクセス](http://penguinitis.g1.xrea.com/computer/programming/AWS/S3_web/S3_web.html)
![20210813構成図](https://user-images.githubusercontent.com/51792606/129286438-c6d61c01-8d99-4aae-978f-8e99274fc277.jpeg)

# 実装したいプログラム
サーバーのgoからcognitoにアクセスしtokenを取得後フロントにtokenを返す。
フロントはそのtokenを用いてs3にアクセス
![構成したい認証図](https://user-images.githubusercontent.com/51792606/129286586-3f285bdc-5e4d-482c-bbe7-230f6d34a896.jpeg)

**Comment by takeru0208** [comment]
tokenをlocal strageに保存してる構造になっているんだけど、local strageにtokenを保存するのは非常にあぶないらしい。
https://techracho.bpsinc.jp/hachi8833/2019_10_09/80851

やはりurlでフロントからimgにアクセスするのではなく、サーバーからencodeしたデータをgetした方が良さげ。

**Comment by littletake** [comment]
> tokenをlocal strageに保存してる構造になっているんだけど、local strageにtokenを保存するのは非常にあぶないらしい。
> https://techracho.bpsinc.jp/hachi8833/2019_10_09/80851
> 
> やはりurlでフロントからimgにアクセスするのではなく、サーバーからencodeしたデータをgetした方が良さげ。

以前話したファイルサーバ的な感じ？

**Comment by littletake** [comment]
こんな感じ？

![IMG_F6DEB2B7025B-1](https://user-images.githubusercontent.com/32430191/130157855-1a03d528-5b0e-4ff2-87f0-71f4ef9cb75e.jpeg)

**Comment by littletake** [comment]
小タスクに切り分けて取り組む
#51 #55

**Comment by littletake** [comment]
### 結論
仕組みとしては[以下の案](https://github.com/littletake/supporterz_hackathon_2021/issues/44#issuecomment-898062905)を採用することにする。
pre-signed urlを使ってフロントがs3から直接画像を取得する方針で。#51

**Comment by littletake** [comment]
### 結論
仕組みとしては[以下の案](https://github.com/littletake/supporterz_hackathon_2021/issues/44#issuecomment-898062905)を採用することにする。
-> 
pre-signed urlを使ってフロントがs3から直接画像を取得する方針

**Comment by littletake** [comment]
# 概要

s3のpre-signed URLを使って制限付きアクセスを実現

# 実装内容

フロント側の画像情報取得時に制限付きURLを発行

アクセス可能時間：1分

# 問題点

- URLは誰でも開くことが可能な点
ユーザ制限の必要あり
- フロント側からのリクエストごとに制限付きURLを発行しているため処理が重い
キャッシュを用いる（ -> 制限時間あるため微妙）  
並列処理（-> 画像の順番は注意すべきか確認する必要あり）
