### ISSUE TITLE
デザインをfigmaに合わせる

### ISSUE THREAD

**Issue by littletake** [littletake/supporterz_hackathon_2021#46]
- [x] ヘッダーの改修
- [x] triplistの改修
- [x] 地図表示の改修

**Comment by littletake** [comment]
自分のPCで試しての感想

**Comment by littletake** [comment]
- [x]  Home画面のヘッダーはなぜ紫陽花の写真？無地でもいいと思う

    ログイン画面のような紺をベースとしたデザインに統一する？

    ただ紺って「フォト旅」感がないかな...？

    写真関連の既存のアプリ（インスタとか）のデザイン真似してもいいかも（黒地のやつ）

-> 
無地に変更

**Comment by littletake** [comment]
- [x]  Top画面、アップロード画面は誰が担当する？

    アップロード画面はヘッダーが消えているのでそこも対応しないといけない

-> 
top画面はおこしが、アップロード画面は一旦保留

**Comment by littletake** [comment]
- [x]  レスポンシブルデザインになっていない

    画面サイズが変わった時にも同じ構図になって欲しい（全体のレイアウトは変わらず文字サイズや各コンポーネントの大きさが変わる感じ）　cssをいじる？フレームワーク使う？

-> 別タスクとしてissueを立てる

**Comment by littletake** [comment]
- [x]  ユーザの設定画面も作る？

    可能ならユーザごと設定できるようにしたいけど、そこまでパーソナライズ考える？

    どんな項目の設定を考える？
->
一旦figmaのデザインに合わせただけ。有無に関しては一旦保留

**Comment by littletake** [comment]
- [x]  Home画面の旅の写真はサムネイルなのでリサイズした画像を別に保存しておく？
（バックエンド対応）

    現状、Home画面のロードが長いように感じるので、これでパフォーマンス改善するかな？
->
時間があれば対応

**Comment by tkumakiri** [comment]
コメントありがとう！
・デザインに関してはfigmaにほぼ合わせていってるのでこんな感じです．デザインの変更はいくらでも効くので適宜指摘してくれると助かります！
・Top画面は多分おこしが担当してくれると思います．アップロード画面は一旦保留中です...
・レスポンシブデザインはスマホと合わせてやろうとしてたので改めてissueを立てようと思ってたところです．
・ユーザー設定もあくまでfigmaに合わせたので削除もできます
・Homeのロードが長いのは多分mapboxで地図を複数読み込んでることが原因だと思う...ただ画像の部分でも遅延原因があるかもしれないので取り組む価値がありそうです！

とりあえずアップロード画面に取り組みつつレスポンシブ対応させようと思います！

**Comment by pola5pola5** [comment]
くまが言うように，Top画面は自分が担当しようと思います！

**Comment by pola5pola5** [comment]
@tkumakiri 
芳賀からも質問出ているけど，figmaの花の背景みたいなやつに合わせて作成したほうがいいのかな？？？？
もしそうだとしたら画像はどこから引いているのか教えて欲しくて，
無地でも問題ないのであれば色の指定があれば教えて欲しい(カラーコード的なやつ)

**Comment by tkumakiri** [comment]
ごめん言うの忘れてたんだけどbranchのfeature/#46_1にデザインを変えたものをpushしたから見てみてほしい！
色は黒基調に変更しました！

**Comment by pola5pola5** [comment]
そこは確認したよ〜
TOPも同じような色で作るイメージってことかな？

**Comment by tkumakiri** [comment]
そうしてくれると助かる！直前の変更で申し訳ないけどお願いします．

**Comment by littletake** [comment]
> ごめん言うの忘れてたんだけどbranchのfeature/#46_1にデザインを変えたものをpushしたから見てみてほしい！
> 色は黒基調に変更しました！

確認しました！シンプルでオシャレになってて良いと思う！

**Comment by littletake** [comment]
とりあえず「figmaに合わせる」タスクでくまが担当している部分に関しては変更完了っていう感じかな？
そしたら一旦developにmergeしようかと思うんだけどどうすか？

アップロード画面とtop画面の修正は別のissueで管理しようかと。

**Comment by tkumakiri** [comment]
返信遅れてごめん！
mergeして大丈夫．助かります！

今週アホみたいに忙しいから土曜日にレスポンシブ対応手をつけます．本当に申し訳ない...

**Comment by pola5pola5** [comment]
> アップロード画面とtop画面の修正は別のissueで管理しようかと。
ならこのissue閉じちゃうね〜
46_1とか46_2でブランチ管理してるのわかりにくいから別で立てるね
