### ISSUE TITLE
フロントで位置情報判定

### ISSUE THREAD

**Issue by pola5pola5** [littletake/supporterz_hackathon_2021#52]

**Comment by littletake** [comment]
# 改善点
- iPhoneから送るときにエラーになる（アップロード時にiPhoneが自動でheicからjpegに変換されているはず）
- ほかの拡張子（png, heic）の対応ができていない

**Comment by littletake** [comment]
アップロードする画像は`.jpeg`に限定
https://github.com/littletake/supporterz_hackathon_2021/issues/59#issuecomment-913089320
