### ISSUE TITLE
ドメインを取得（https化）

### ISSUE THREAD

**Issue by takeru0208** [littletake/supporterz_hackathon_2021#53]
インスタンスを停止してから再開すると public ipが変わりアクセスしにくいし、プログラムも変えないといけない。

Route 53などで固定ipを取得するべきか、料金や手間などと要相談

ip固定のqiitaの記事
https://qiita.com/mat827/items/f13876340435674aa340

**Comment by littletake** [comment]
ALB + ACM + Route53を使って実現
