### ISSUE TITLE
aws cognitoを使ったユーザー認証

### ISSUE THREAD

**Issue by takeru0208** [littletake/supporterz_hackathon_2021#54]
現在ユーザープールがサーバー内にあるが、これをaws cogniteを使ってaws上にユーザープールを作成するという案がある。
ぜひ導入を検討したい。

aws cogniteを使う利点は以下である。
* サーバーからawsサービスへの接続に認証を追加できる
* パスワードの強度指定をできる（英数8文字以上など）
* emailの認証がデフォルトで入っているので、現在のパスワード認証よりも安全。
* 他端末(androidなど）を追加した際に、同じユーザーでアクセスするのが簡単になる。

欠点としては以下
* 実装時間
* 料金がかかる

**Comment by littletake** [comment]
こんな感じ？？？

![IMG_97B8FE3EA749-1](https://user-images.githubusercontent.com/32430191/132243435-4c0d441f-4c88-4353-ab72-5b14b1eb7f1f.jpeg)
